server:
  port: 8888
#数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 
    url: jdbc:mysql://localhost/device?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  messages:
    basename: i18n.login

mybatis-plus:
  type-aliases-package: com.strQeem.pojo

